Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using web_shop_app.Data;
using web_shop_app.Models;

namespace web_shop_app.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Admin/Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            try
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {

                return View(category);
            }
               
            
        }

        // GET: Admin/Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));

        }

        // GET: Admin/Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using web_shop_app.Data;
using web_shop_app.Models;
using web_shop_app.ViewModels;

namespace web_shop_app.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Order
        public async Task<IActionResult> Index()
        {
            return View(await _context.Orders.ToListAsync());
        }

        // GET: Admin/Order/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.Id == id);

            if (order == null)
            {
                return NotFound();
            }

            order.OrderItems = (
                from orderItem in _context.OrderItems
                where orderItem.OrderId == order.Id
                select new OrderItem
                {
                    Id = orderItem.Id,
                    OrderId = orderItem.OrderId,
                    ProductId = orderItem.ProductId,
                    Quantity = orderItem.Quantity,
                    Total = orderItem.Total,
                    ProductTitle = (from product in _context.Products where product.Id == orderItem.ProductId select product.Title).FirstOrDefault()
                }
               ).ToList();

            

            return View(order);
        }

        // GET: Admin/Order/Create
        public IActionResult Create()
        {
            ViewBag.Users = _context.Users.Select(
                 user => new SelectListItem
                 {
                     Value = user.Id.ToString(),
                     Text = user.FirstName + " " + user.LastName,
                 }
             ).ToList();

            return View();
        }

        // POST: Admin/Order/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OrderViewModel orderViewModel)
        {
            try
            {
                var order = new Order()
                {   
                    Message = orderViewModel.Message,
                    UserId = orderViewModel.UserId,
                    BillingAddress = orderViewModel.OrderAddress.BillingAddress,
                    BillingCity = orderViewModel.OrderAddress.BillingCity,
                    BillingEmail = orderViewModel.OrderAddress.BillingEmail,
                    BillingCountry = orderViewModel.OrderAddress.BillingCountry,
                    BillingFirstName = orderViewModel.OrderAddress.BillingFirstName,
                    BillingLastName = orderViewModel.OrderAddress.BillingLastName,
                    BillingPhone = orderViewModel.OrderAddress.BillingPhone,
                    BillingZip = orderViewModel.OrderAddress.BillingZip,
                };


                _context.Add(order);
                await _context.SaveChangesAsync();

                return RedirectToAction("Details", new {id = order.Id});
            }
            catch (Exception)
            {
                return View(orderViewModel);
            }
              
       
        }

        // GET: Admin/Order/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            var userOnOrder = await _context.Users.FirstOrDefaultAsync(user => user.Id == order.UserId);

            var orderViewModel = new OrderViewModel()
            {
                Id = order.Id,
                Total = order.Total,
                UserId = order.UserId,
                DateCreated = order.DateCreated,
                Message = order.Message,
                OrderAddress = new OrderAddress()
                {
                    BillingAddress = order.BillingAddress,
                    BillingCity = order.BillingCity,
                    BillingCountry = order.BillingCountry,
                    BillingZip = order.BillingZip,
                    BillingEmail = order.BillingEmail,
                    BillingPhone = order.BillingPhone,
                    BillingFirstName = order.BillingFirstName,
                    BillingLastName = order.BillingLastName
                }
            };

            string? user = null;

            if (userOnOrder != null)
            {
                user = userOnOrder.FirstName + " " + userOnOrder.LastName;
            }
            else
            {
                user = order.BillingFirstName + " " + order.BillingLastName;
            }

            ViewBag.User = user;

            if (order == null)
            {
                return NotFound();
            }
            return View(orderViewModel);
        }

        // POST: Admin/Order/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, OrderViewModel orderViewModel)
        {
            if (id != orderViewModel.Id)
            {
                return NotFound();
            }

            Order order = new Order();

            try
            {
                order = _context.Orders.FirstOrDefault(order => order.Id == id);

                if (order == null)
                {
                    return NotFound();
                }

                order.BillingAddress = orderViewModel.OrderAddress.BillingAddress;
                order.BillingCity = orderViewModel.OrderAddress.BillingCity;
                order.BillingZip = orderViewModel.OrderAddress.BillingZip;
                order.BillingCountry = orderViewModel.OrderAddress.BillingCountry;
                order.BillingPhone = orderViewModel.OrderAddress.BillingPhone;
                order.BillingEmail = orderViewModel.OrderAddress.BillingEmail;
                order.BillingLastName = orderViewModel.OrderAddress.BillingLastName;
                order.BillingFirstName = orderViewModel.OrderAddress.BillingFirstName;


                _context.Update(order);
                await _context.SaveChangesAsync();

            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrderExists(id))
                {
                    return NotFound();
                }
                else
                {
                    return View(order);
                }
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Admin/Order/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Admin/Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }
    }
}

Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using web_shop_app.Data;
using web_shop_app.Extensions;
using web_shop_app.Models;

namespace web_shop_app.Controllers
{
    public class CartController : Controller
    {
        public const string SessionKeyName = "_cart";

        private readonly ApplicationDbContext _context;

        public CartController(ApplicationDbContext context)
        {
           _context = context;
        }
        public IActionResult Index()
        {
            List<CartItem> cart =
                HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName) ?? new List<CartItem>();

            decimal total = 0;

            ViewBag.Cart = cart;
            ViewBag.TotalPrice = cart.Sum(item => total + item.GetTotal());
            ViewBag.ShouldShowRemoveAction = true;

            return View();
        }


        public IActionResult AddToCart(int productId, int selectedQuantity)
        {
            List<CartItem> sessionCartItems = 
                HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName) ?? new List<CartItem>();

            if(sessionCartItems.Count == 0)
            {
                CartItem cartItem = new CartItem
                {
                    Product =  _context.Products.Find(productId),
                    Quantity = selectedQuantity
                };

                sessionCartItems.Add(cartItem);
            }
            else
            {
                int productIndex = IsExistingInCart(productId);

                if(productIndex == -1)
                {
                    CartItem cartItem = new CartItem
                    {
                        Product = _context.Products.Find(productId),
                        Quantity = selectedQuantity
                    };

                    sessionCartItems.Add(cartItem);
                }
                else
                {
                    sessionCartItems[productIndex].IncreaseQuantity(selectedQuantity);
                }
            }

            HttpContext.Session.SetObjectAsJson(SessionKeyName, sessionCartItems);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult RemoveFromCart(int productId)
        {
            List<CartItem> sessionCart = HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName)
                ?? new List<CartItem>();

            int productIndex = IsExistingInCart(productId);

            if(productIndex == -1)
            {
                return NotFound();
            }

            sessionCart.RemoveAt(productIndex);

            HttpContext.Session.SetObjectAsJson(SessionKeyName, sessionCart);

            return RedirectToAction(nameof(Index));

        }

        private int IsExistingInCart(int productId)
        {
            List<CartItem> cart = HttpContext.Session.GetObjectFromJson<List<CartItem>>(SessionKeyName);

            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id == productId)
                {
                    return i;
                }
            }

            return -1;
        }
    }
}

Views/Shared/_AdminMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using web_shop_app.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(UserManager.GetUserAsync(User).Result,"admin"))
{
    <li class="nav-item">
        <div class="dropdown">
            <a class="nav-link text-dark dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button">Admin</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
                <a class="dropdown-item" asp-area="Admin" asp-controller="Order" asp-action="Index">Orders</a>
            </div>
        </div>
    </li>
}

Views/Shared/_CartPartial.cshtml
@model List<CartItem>

<table class="table">
    <thead>
        <tr>
            @if (ViewBag.ShouldShowRemoveAction)
            {
                <th></th>
            }
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @if (ViewBag.ShouldShowRemoveAction)
                {
                    <td>
                        <a class="btn btn-danger" asp-action="RemoveFromCart" asp-route-productId="@item.Product.Id">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z" />
                                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z" />
                            </svg>
                            Remove
                        </a>
                    </td>
                }
                
                <td>@item.Product.Title</td>
                <td>@item.Product.Price.ToString("0.00") €</td>
                <td>@item.Quantity</td>
                <td>@item.GetTotal().ToString("0.00") €</td>
            </tr>
        }
        <tr>
            @if (ViewBag.ShouldShowRemoveAction)
            {
                <td></td>
            }            
            <td></td>
            <td></td>
            <td></td>
            <td class="fw-bold"> Total price: @ViewBag.TotalPrice.ToString("0.00") € </td>
        </tr>

    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - web_shop_app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/web_shop_app.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">web_shop_app</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <partial name="_PublicMenuPartial" />
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <partial name="_AdminMenuPartial" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - web_shop_app - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_PublicMenuPartial.cshtml
<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Products">Products</a>
</li>
<li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
</li>