Models/Order.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace web_shop_app.Models
{
    public class Order
    {

        public Order()
        {
            DateCreated = DateTime.Now;
            Total = 0.00M;
        }

        public int Id { get; set; }

        public DateTime DateCreated { get; private set; }

        [Column(TypeName = "decimal(9, 2)")]
        public decimal Total { get; set; }

        [StringLength(50)]
        public string BillingFirstName { get; set; }

        [StringLength(50)]
        public string BillingLastName { get; set; }

        [StringLength(100)]
        public string BillingEmail { get; set; }

        [StringLength(100)]
        public string BillingPhone { get; set; }

        [StringLength(150)]
        public string BillingAddress { get; set; }

        [StringLength(50)]
        public string BillingCity { get; set; }

        [StringLength(50)]
        public string BillingCountry { get; set; }

        [StringLength(20)]
        public string BillingZip { get; set; }
       
        public string? Message { get; set; }

        public string? UserId { get; set; }

        [ForeignKey("OrderId")]
        public ICollection<OrderItem> OrderItems { get; set; }
    }
}

ViewModels/OrderViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace web_shop_app.ViewModels
{
    public class OrderViewModel
    {
        public int Id { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateCreated { get; set; }

        [Required(ErrorMessage = "Total price is required.")]
        [Column(TypeName = "decimal(9, 2)")]
        public decimal Total { get; set; }

        public string Message { get; set; }

        public string UserId { get; set; }

        public OrderAddress OrderAddress { get; set; }
    }
}

Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using web_shop_app.Data;
using web_shop_app.Models;
using web_shop_app.ViewModels;

namespace web_shop_app.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Order
        public async Task<IActionResult> Index()
        {
            return View(await _context.Orders.ToListAsync());
        }

        // GET: Admin/Order/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.Id == id);

            if (order == null)
            {
                return NotFound();
            }

            order.OrderItems = (
                from orderItem in _context.OrderItems
                where orderItem.OrderId == order.Id
                select new OrderItem
                {
                    Id = orderItem.Id,
                    OrderId = orderItem.OrderId,
                    ProductId = orderItem.ProductId,
                    Quantity = orderItem.Quantity,
                    Total = orderItem.Total,
                    ProductTitle = (from product in _context.Products where product.Id == orderItem.ProductId select product.Title).FirstOrDefault()
                }
               ).ToList();

            

            return View(order);
        }

        // GET: Admin/Order/Create
        public IActionResult Create()
        {
            ViewBag.Users = _context.Users.Select(
                 user => new SelectListItem
                 {
                     Value = user.Id.ToString(),
                     Text = user.FirstName + " " + user.LastName,
                 }
             ).ToList();

            return View();
        }

        // POST: Admin/Order/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OrderViewModel orderViewModel)
        {
            try
            {
                var order = new Order()
                {   
                    Message = orderViewModel.Message,
                    UserId = orderViewModel.UserId,
                    BillingAddress = orderViewModel.OrderAddress.BillingAddress,
                    BillingCity = orderViewModel.OrderAddress.BillingCity,
                    BillingEmail = orderViewModel.OrderAddress.BillingEmail,
                    BillingCountry = orderViewModel.OrderAddress.BillingCountry,
                    BillingFirstName = orderViewModel.OrderAddress.BillingFirstName,
                    BillingLastName = orderViewModel.OrderAddress.BillingLastName,
                    BillingPhone = orderViewModel.OrderAddress.BillingPhone,
                    BillingZip = orderViewModel.OrderAddress.BillingZip,
                };


                _context.Add(order);
                await _context.SaveChangesAsync();

                return RedirectToAction("Details", new {id = order.Id});
            }
            catch (Exception)
            {
                return View(orderViewModel);
            }
              
       
        }

        // GET: Admin/Order/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            var userOnOrder = await _context.Users.FirstOrDefaultAsync(user => user.Id == order.UserId);

            var orderViewModel = new OrderViewModel()
            {
                Id = order.Id,
                Total = order.Total,
                UserId = order.UserId,
                DateCreated = order.DateCreated,
                Message = order.Message,
                OrderAddress = new OrderAddress()
                {
                    BillingAddress = order.BillingAddress,
                    BillingCity = order.BillingCity,
                    BillingCountry = order.BillingCountry,
                    BillingZip = order.BillingZip,
                    BillingEmail = order.BillingEmail,
                    BillingPhone = order.BillingPhone,
                    BillingFirstName = order.BillingFirstName,
                    BillingLastName = order.BillingLastName
                }
            };

            string? user = null;

            if (userOnOrder != null)
            {
                user = userOnOrder.FirstName + " " + userOnOrder.LastName;
            }
            else
            {
                user = order.BillingFirstName + " " + order.BillingLastName;
            }

            ViewBag.User = user;

            if (order == null)
            {
                return NotFound();
            }
            return View(orderViewModel);
        }

        // POST: Admin/Order/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, OrderViewModel orderViewModel)
        {
            if (id != orderViewModel.Id)
            {
                return NotFound();
            }

            Order order = new Order();

            try
            {
                order = _context.Orders.FirstOrDefault(order => order.Id == id);

                if (order == null)
                {
                    return NotFound();
                }

                order.BillingAddress = orderViewModel.OrderAddress.BillingAddress;
                order.BillingCity = orderViewModel.OrderAddress.BillingCity;
                order.BillingZip = orderViewModel.OrderAddress.BillingZip;
                order.BillingCountry = orderViewModel.OrderAddress.BillingCountry;
                order.BillingPhone = orderViewModel.OrderAddress.BillingPhone;
                order.BillingEmail = orderViewModel.OrderAddress.BillingEmail;
                order.BillingLastName = orderViewModel.OrderAddress.BillingLastName;
                order.BillingFirstName = orderViewModel.OrderAddress.BillingFirstName;


                _context.Update(order);
                await _context.SaveChangesAsync();

            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrderExists(id))
                {
                    return NotFound();
                }
                else
                {
                    return View(order);
                }
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Admin/Order/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Admin/Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.Id == id);
        }
    }
}

Areas/Admin/Controllers/OrderItemController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using web_shop_app.Data;
using web_shop_app.Models;

namespace web_shop_app.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class OrderItemController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderItemController(ApplicationDbContext context)
        {
            _context = context;
        }


        // GET: Admin/OrderItem/Create
        public IActionResult Create(int orderId)
        {
            ViewBag.OrderId = orderId;  

            ViewBag.Products = _context.Products.Select(
            product => new SelectListItem
            {
                Value = product.Id.ToString(),
                Text = product.Title

            }).ToList();

            return View();
        }

        // POST: Admin/OrderItem/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( OrderItem orderItem)
        {
            try
            {
                var productDetails = _context.Products
                    .Where(p => p.Id == orderItem.ProductId)
                    .SingleOrDefault();

                if (productDetails == null){ 

                    return NotFound();
                }

                var order = await _context.Orders.FirstOrDefaultAsync(o => o.Id == orderItem.OrderId);

                if (order == null)
                {
                    return NotFound();
                }

                orderItem.Total = orderItem.Quantity * productDetails.Price;
                order.Total = order.Total + orderItem.Total;

                // order.Total += orderItem.Total --- kraće----


                await _context.AddAsync(orderItem);
                 _context.Update(order);
                
                await _context.SaveChangesAsync();
                return RedirectToAction("Details","Order", new { id =  orderItem.OrderId});
            }
            catch (Exception)
            {

                return View(orderItem);
            }
          
        }


        // GET: Admin/OrderItem/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItems
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        // POST: Admin/OrderItem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
             var orderItem = await _context.OrderItems.FindAsync(id);

            if(orderItem == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(orderItem.OrderId);

            if (order == null)
            {
                return NotFound();
            }

            order.Total = order.Total - orderItem.Total;

            if (orderItem != null)
            {
                _context.OrderItems.Remove(orderItem);
            }

            _context.Update(order);

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Order", new { id = orderItem.OrderId });
        }

        private bool OrderItemExists(int id)
        {
            return _context.OrderItems.Any(e => e.Id == id);
        }
    }
}

Areas/Admin/Views/Order/Create.cshtml
@model web_shop_app.ViewModels.OrderViewModel

@{
    ViewData["Title"] = "Create";
}

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingFirstName" class="control-label"></label>
                <input asp-for="OrderAddress.BillingFirstName" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingLastName" class="control-label"></label>
                <input asp-for="OrderAddress.BillingLastName" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingEmail" class="control-label"></label>
                <input asp-for="OrderAddress.BillingEmail" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingPhone" class="control-label"></label>
                <input asp-for="OrderAddress.BillingPhone" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingAddress" class="control-label"></label>
                <input asp-for="OrderAddress.BillingAddress" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingCity" class="control-label"></label>
                <input asp-for="OrderAddress.BillingCity" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingCountry" class="control-label"></label>
                <input asp-for="OrderAddress.BillingCountry" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingZip" class="control-label"></label>
                <input asp-for="OrderAddress.BillingZip" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingZip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label">User</label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.Users"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/Order/Delete.cshtml
@model web_shop_app.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingFirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingFirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingCountry)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingCountry)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingZip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingZip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Areas/Admin/Views/Order/Details.cshtml
@model web_shop_app.Models.Order

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    
    <h4>Order <a asp-action="Create" asp-controller="OrderItem" asp-route-orderId="@Model.Id"> + Add order item</a></h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingFirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingFirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingCity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingCity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingCountry)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingCountry)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BillingZip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BillingZip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
    <partial name="_OrderItemsPartial" for="@Model.OrderItems" />
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/Order/Edit.cshtml
@model web_shop_app.ViewModels.OrderViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="UserId" />
            <div class="form-group">
                <label asp-for="OrderAddress.BillingFirstName" class="control-label"></label>
                <input asp-for="OrderAddress.BillingFirstName" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingLastName" class="control-label"></label>
                <input asp-for="OrderAddress.BillingLastName" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingEmail" class="control-label"></label>
                <input asp-for="OrderAddress.BillingEmail" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingPhone" class="control-label"></label>
                <input asp-for="OrderAddress.BillingPhone" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingAddress" class="control-label"></label>
                <input asp-for="OrderAddress.BillingAddress" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingCity" class="control-label"></label>
                <input asp-for="OrderAddress.BillingCity" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingCity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingCountry" class="control-label"></label>
                <input asp-for="OrderAddress.BillingCountry" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderAddress.BillingZip" class="control-label"></label>
                <input asp-for="OrderAddress.BillingZip" class="form-control" />
                <span asp-validation-for="OrderAddress.BillingZip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">User</label>
                <input type="text" disabled class="form-control" value="@ViewBag.User" />
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/Order/Index.cshtml
@model IEnumerable<web_shop_app.Models.Order>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillingFirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillingLastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillingEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillingPhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillingAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillingCity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillingCountry)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillingZip)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Message)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Total)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BillingFirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BillingLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BillingEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BillingPhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BillingAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BillingCity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BillingCountry)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BillingZip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Message)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>